connection:
  socket: /tmp/agentx
  agent_timeout_seconds: 100
oid_base: [1, 3, 6, 1, 4, 1, <pen>]
#commands:
#  - mib: 1.3.6.1.4.1.pen
#    command: rocm-smi --showallinfo --json
#    # todo: handle instances
#    mibs:
#      - mib: 1.3.6.1.4.1.pen.2.1
#        json_path: $.card0["Device Name"]
#        data_type: string
#      - mib: 1.3.6.1.4.1.pen.5.1
#        json_path: $.card0["Temperature (Sensor edge) (C)"]
#        data_type: integer
#        convert: multiply_by_1000
